import logging

from django.utils import timezone
from drf_spectacular.utils import extend_schema, OpenApiResponse, inline_serializer
from rest_framework import status, serializers as drf_serializers
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.authentication.permissions import IsHealthWorker
from apps.patients.models import Patient
from services.ai_engine.interview_engine import InterviewEngine
from services.tts.manager import generate_dynamic_audio

from .models import AssessmentSession, AssessmentResponse, AssessmentStatus, AssessmentPriority
from .serializers import StartAssessmentSerializer, RespondSerializer, AssessmentSessionSerializer

logger = logging.getLogger('apps.assessment')

_engine = InterviewEngine()


class StartAssessmentView(APIView):
    permission_classes = [IsAuthenticated, IsHealthWorker]

    @extend_schema(
        request=StartAssessmentSerializer,
        responses={
            201: inline_serializer('StartResponse', fields={
                'session_id': drf_serializers.UUIDField(),
                'turn': drf_serializers.IntegerField(),
                'question_text': drf_serializers.CharField(),
                'audio_url': drf_serializers.CharField(allow_null=True),
                'status': drf_serializers.CharField(),
            }),
        },
        summary='Start a new AI-driven assessment session',
        description=(
            'Creates a new AssessmentSession for a patient and returns the opening question '
            'generated by the AI Clinical Interview Engine. The health worker must own the patient.'
        ),
    )
    def post(self, request):
        serializer = StartAssessmentSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        patient_id = serializer.validated_data['patient_id']
        language = serializer.validated_data['language']

        qs = Patient.objects.filter(pk=patient_id, is_active=True)
        if not request.user.is_admin:
            qs = qs.filter(health_worker=request.user)

        try:
            patient = qs.get()
        except Patient.DoesNotExist:
            return Response(
                {'detail': 'Patient not found.'},
                status=status.HTTP_404_NOT_FOUND,
            )

        # Opening question — no API call, personalised with patient name + time greeting
        result = _engine.opening_question(language, patient_name=patient.first_name)

        session = AssessmentSession.objects.create(
            patient=patient,
            health_worker=request.user,
            language=language,
            current_question=result.question,
            status=AssessmentStatus.IN_PROGRESS,
            conversation_history=_engine.initial_history(language),
        )

        audio_url = generate_dynamic_audio(
            text=result.question,
            language=language,
            session_id=str(session.id),
            turn=0,
        )

        logger.info('Assessment session %s started by %s', session.id, request.user.email)

        return Response({
            'session_id': session.id,
            'turn': 0,
            'question_text': result.question,
            'audio_url': audio_url,
            'status': 'in_progress',
        }, status=status.HTTP_201_CREATED)


class RespondView(APIView):
    permission_classes = [IsAuthenticated, IsHealthWorker]

    @extend_schema(
        request=RespondSerializer,
        responses={
            200: inline_serializer('RespondResponse', fields={
                'session_id': drf_serializers.UUIDField(),
                'turn': drf_serializers.IntegerField(),
                'question_text': drf_serializers.CharField(allow_null=True),
                'audio_url': drf_serializers.CharField(allow_null=True),
                'status': drf_serializers.CharField(),
                'assessment_priority': drf_serializers.CharField(allow_null=True),
                'assessment_report': drf_serializers.CharField(allow_null=True),
            }),
        },
        summary='Submit a patient answer and advance the AI interview',
        description=(
            'Accepts the patient\'s transcribed answer, saves it, then calls the AI engine '
            'to determine the next question. Returns status="completed" with the clinical '
            'assessment report when the AI decides enough information has been collected.'
        ),
    )
    def post(self, request):
        serializer = RespondSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        session_id = serializer.validated_data['session_id']
        answer_text = serializer.validated_data['answer_text']

        qs = AssessmentSession.objects.filter(
            pk=session_id,
            status=AssessmentStatus.IN_PROGRESS,
        )
        if not request.user.is_admin:
            qs = qs.filter(health_worker=request.user)

        try:
            session = qs.get()
        except AssessmentSession.DoesNotExist:
            return Response(
                {'detail': 'Active session not found.'},
                status=status.HTTP_404_NOT_FOUND,
            )

        # Current turn number = number of responses already saved
        turn = session.responses.count()
        question_key = f'turn_{turn}'

        # Save the patient's answer for this turn
        AssessmentResponse.objects.create(
            session=session,
            question_key=question_key,
            question_text=session.current_question,
            answer_text=answer_text,
            extracted_value=None,  # NLP extraction — Phase 8
        )

        logger.info('Session %s — response saved for %s', session.id, question_key)

        # Call the AI engine with the existing history + this answer
        result = _engine.next_turn(
            conversation_history=session.conversation_history,
            patient_answer=answer_text,
            language=session.language,
        )

        if result.status == 'completed':
            priority = result.priority if result.priority in ('NORMAL', 'URGENT') else 'NORMAL'
            session.status = AssessmentStatus.COMPLETED
            session.completed_at = timezone.now()
            session.assessment_report = result.report
            session.assessment_priority = priority
            session.conversation_history = session.conversation_history + [
                {"role": "user", "parts": [{"text": answer_text}]},
            ]
            session.save(update_fields=[
                'status', 'completed_at', 'assessment_report',
                'assessment_priority', 'conversation_history',
            ])
            logger.info('Session %s completed — priority: %s', session.id, priority)

            completion_msg = _engine.completion_message(session.language, priority)
            completion_audio = generate_dynamic_audio(
                text=completion_msg,
                language=session.language,
                session_id=str(session.id),
                turn='complete',
            )

            return Response({
                'session_id': session.id,
                'turn': turn + 1,
                'status': 'completed',
                'assessment_priority': priority,
                'assessment_report': result.report,
                'completion_message': completion_msg,
                'completion_audio_url': completion_audio,
            })

        # Interview continues — advance to next question
        next_turn = turn + 1
        updated_history = session.conversation_history + [
            {"role": "user",  "parts": [{"text": answer_text}]},
            {"role": "model", "parts": [{"text": result.question}]},
        ]

        session.current_question = result.question
        session.conversation_history = updated_history
        session.save(update_fields=['current_question', 'conversation_history'])

        audio_url = generate_dynamic_audio(
            text=result.question,
            language=session.language,
            session_id=str(session.id),
            turn=next_turn,
        )

        return Response({
            'session_id': session.id,
            'turn': next_turn,
            'question_text': result.question,
            'audio_url': audio_url,
            'status': 'in_progress',
            'assessment_priority': None,
            'assessment_report': None,
        })


class SessionDetailView(APIView):
    permission_classes = [IsAuthenticated, IsHealthWorker]

    @extend_schema(
        responses={200: AssessmentSessionSerializer},
        summary='Get full session detail',
        description='Returns the full assessment session including all recorded responses and the assessment report if completed.',
    )
    def get(self, request, session_id):
        qs = AssessmentSession.objects.prefetch_related('responses')
        if not request.user.is_admin:
            qs = qs.filter(health_worker=request.user)

        try:
            session = qs.get(pk=session_id)
        except AssessmentSession.DoesNotExist:
            return Response(
                {'detail': 'Session not found.'},
                status=status.HTTP_404_NOT_FOUND,
            )

        return Response(AssessmentSessionSerializer(session).data)
