# Generated by Django 6.0.5 on 2026-06-02 01:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("pcm", "Pidgin English"),
                        ],
                        max_length=3,
                    ),
                ),
                ("current_question", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "health_worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Session",
                "verbose_name_plural": "Assessment Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_key", models.CharField(max_length=50)),
                ("answer_text", models.TextField()),
                ("extracted_value", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="assessment.assessmentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Response",
                "verbose_name_plural": "Assessment Responses",
                "ordering": ["created_at"],
                "unique_together": {("session", "question_key")},
            },
        ),
    ]
