# Generated by Django 6.0.5 on 2026-06-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentresponse",
            name="question_text",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="assessment_priority",
            field=models.CharField(
                choices=[("NORMAL", "Normal"), ("URGENT", "Urgent")],
                default="NORMAL",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="assessment_report",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="conversation_history",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="assessmentsession",
            name="current_question",
            field=models.TextField(default=""),
        ),
    ]
