'use client'

import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { ArrowLeft, Download, AlertTriangle, CheckCircle, Loader2 } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Skeleton } from '@/components/ui/skeleton'
import api from '@/lib/api'
import { AssessmentSession } from '@/types'

const LANGUAGE_LABELS: Record<string, string> = { en: 'English', fr: 'French', pcm: 'Pidgin' }
const API_BASE = process.env.NEXT_PUBLIC_API_URL?.replace('/api/v1', '') || 'http://127.0.0.1:8000'

export default function ReportPage() {
  const { id } = useParams<{ id: string }>()
  const router = useRouter()
  const [session, setSession] = useState<AssessmentSession | null>(null)
  const [loading, setLoading] = useState(true)
  const [downloading, setDownloading] = useState(false)

  useEffect(() => {
    api.get<AssessmentSession>(`/assessment/sessions/${id}/`)
      .then((r) => setSession(r.data))
      .catch(() => toast.error('Failed to load report.'))
      .finally(() => setLoading(false))
  }, [id])

  async function handleDownloadPDF() {
    setDownloading(true)
    try {
      const response = await api.get(`/reports/${id}/pdf/`, { responseType: 'blob' })
      const url = URL.createObjectURL(new Blob([response.data], { type: 'application/pdf' }))
      const a = document.createElement('a')
      a.href = url
      a.download = `meditok-report-${id.slice(0, 8)}.pdf`
      a.click()
      URL.revokeObjectURL(url)
      toast.success('PDF downloaded.')
    } catch {
      toast.error('PDF generation failed.')
    } finally {
      setDownloading(false)
    }
  }

  if (loading) {
    return (
      <div className="max-w-2xl mx-auto space-y-4">
        <Skeleton className="h-8 w-48" />
        <Skeleton className="h-64 w-full" />
      </div>
    )
  }

  if (!session) return null

  const isUrgent = session.assessment_priority === 'URGENT'

  return (
    <div className="max-w-2xl mx-auto space-y-5">
      {/* Back button */}
      <Button variant="ghost" size="sm" onClick={() => router.push('/assessment')} className="gap-2 -ml-2">
        <ArrowLeft className="h-4 w-4" /> All Assessments
      </Button>

      {/* Header card */}
      <Card className={`border-2 ${isUrgent ? 'border-red-400' : ''}`}
        style={!isUrgent ? { borderColor: '#00B89C' } : undefined}>
        <CardHeader className="pb-3">
          <div className="flex items-start justify-between gap-4 flex-wrap">
            <div className="space-y-1">
              <CardTitle className="text-xl">
                {session.patient.first_name} {session.patient.last_name}
              </CardTitle>
              <div className="flex flex-wrap gap-2 text-sm text-muted-foreground">
                <span>{LANGUAGE_LABELS[session.language]} interview</span>
                <span>·</span>
                <span>{new Date(session.started_at).toLocaleDateString('en-GB', {
                  day: 'numeric', month: 'long', year: 'numeric',
                })}</span>
                {session.completed_at && (
                  <>
                    <span>·</span>
                    <span>Completed {new Date(session.completed_at).toLocaleTimeString([], {
                      hour: '2-digit', minute: '2-digit',
                    })}</span>
                  </>
                )}
              </div>
            </div>

            <div className="flex items-center gap-2">
              {isUrgent ? (
                <Badge variant="destructive" className="gap-1.5 text-sm px-3 py-1">
                  <AlertTriangle className="h-4 w-4" /> URGENT
                </Badge>
              ) : (
                <Badge className="gap-1.5 text-sm px-3 py-1 text-white" style={{ backgroundColor: '#00B89C' }}>
                  <CheckCircle className="h-4 w-4" /> Normal
                </Badge>
              )}
            </div>
          </div>
        </CardHeader>
      </Card>

      {/* Download PDF */}
      <Button
        onClick={handleDownloadPDF}
        disabled={downloading}
        className="w-full gap-2 text-white font-semibold h-11"
        style={{ backgroundColor: '#1B3A6B' }}
      >
        {downloading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
        {downloading ? 'Generating PDF…' : 'Download PDF Report'}
      </Button>

      {/* Report text */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-base">Clinical Assessment Report</CardTitle>
          <p className="text-xs text-muted-foreground">
            Generated by MediTok AI · For review by a healthcare professional only
          </p>
        </CardHeader>
        <CardContent>
          {session.assessment_report ? (
            <pre className="whitespace-pre-wrap text-sm leading-relaxed font-sans text-foreground">
              {session.assessment_report}
            </pre>
          ) : (
            <p className="text-sm text-muted-foreground">No report available.</p>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
